POST http://localhost:3003/
Content-Type: application/json

{
    "nome": "Rubinho",
    "modulo": 0
}
###
GET  http://localhost:3003/
Content-Type: application/json
###

PUT http://localhost:3003/turma/1650658151895
Content-Type: application/json

{
    "modulo": 1
}
###
POST http://localhost:3003/estudante/1650657422722
Content-Type: application/json

{
    "nome": "Enzo",
    "email": "enzo@labenu",
    "data_nasc": "02/04/2002"
}
###
GET  http://localhost:3003/estudante?nome="Eliel"
Content-Type: application/json
###
PUT http://localhost:3003/:id/:turmaId
Content-Type: application/json

{
    "modulo": 1
}